# .github/workflows/docker-ci.yml
# This workflow automates building and pushing Docker images for FinTrack.

name: Docker CI

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests to 'main' for validation

env:
  # Docker image names (adjust as needed)
  BACKEND_IMAGE_NAME: finance-track-backend
  FRONTEND_IMAGE_NAME: finance-track-frontend
  
  # Docker Hub username (replace with your actual Docker Hub username)
  # This should match the username you used to log in via 'docker login'
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }} # Stored as a GitHub Secret

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a GitHub-hosted runner with Ubuntu

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Checkout the source code

    - name: Log in to Docker Hub
      uses: docker/login-action@v3 # Action to log in to Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }} # Stored as a GitHub Secret

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5 # Action to build and push Docker images
      with:
        context: ./Backend # Path to your backend directory
        file: ./Backend/Dockerfile # Path to your backend Dockerfile
        push: true # Enable pushing to registry
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.run_id }} # Tag with unique run ID
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest # Tag as latest

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./finance-tracker-frontend # Path to your frontend directory
        file: ./finance-tracker-frontend/Dockerfile # Path to your frontend Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.run_id }}
          ${{ env.DOCKER_HUB_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest

    # Optional: Add a deployment step here if you want to automate deployment after building
    # For example, to Azure Container Instances (ACI) or Azure Kubernetes Service (AKS)
    # This would require additional GitHub Actions for Azure deployment.
